name: flashcards_app_flutter
description: Simple cross-platform flashcards demo (web + mobile/desktop)
publish_to: 'none'
version: 1.0.2+7

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  image_picker: ^1.1.2
  file_picker: ^10.3.1
  shared_preferences: ^2.3.2
  share_plus: ^11.1.0
  cross_file: ^0.3.4+2
  path_provider: ^2.1.4
  flutter_file_dialog: ^3.0.0
  image: ^4.2.0
  archive: ^4.0.7
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
